theme = "catppuccin_mocha"

[editor]
auto-pairs = false
bufferline = "always"
color-modes = true
line-number = "relative"
true-color = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

"A-h" = "goto_previous_buffer"
"A-l" = "goto_next_buffer"

"A-/" = "toggle_comments"

"space" = { x = ":buffer-close", X = ":buffer-close-others" }

"C-." = "completion"

[keys.select]
"C-." = "completion"

[keys.insert]
"C-j" = "code_action"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
